### ISSUE TITLE
install directions

### ISSUE THREAD

**Issue by ragesaq** [bigg33k/smoke2graphite#1]
I am very interested in running smoke2graphite, do you have an install guide/notes?

**Comment by bigg33k** [comment]
Hi there,
There really isn't much to it. Ensure statsd is installed (python-statsd)
and ensure the config is set correct. The readme has the cron entry that
i'm running.
Feel free to fork and improve.
LMK if you have any questions.

On 9 April 2016 at 18:28, ragesaq notifications@github.com wrote:

> I am very interested in running smoke2graphite, do you have an install
> guide/notes?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/bigg33k/smoke2graphite/issues/1

## 

Dave Lemaire
603-325-2257

**Comment by ragesaq** [comment]
Tried that, I got this and I figured I was missing something.

Traceback (most recent call last):
  File "./s2g.py", line 86, in <module>
    response=subprocess.Popen(['rrdtool', 'lastupdate',f], stdout=subprocess.PIPE).communicate()[0]
  File "/usr/lib/python2.7/subprocess.py", line 710, in **init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception

**Comment by bigg33k** [comment]
hrm.
I've made a couple small tweaks since checking that it, but the Popen
hasn't changed. do you have rrdtool installed?
I'll update the code when I get a few minutes.

On 9 April 2016 at 19:59, ragesaq notifications@github.com wrote:

> Tried that, I get this and I figured I was missing something.
> 
> Traceback (most recent call last):
> File "./s2g.py", line 86, in
> response=subprocess.Popen(['rrdtool', 'lastupdate',f],
> stdout=subprocess.PIPE).communicate()[0]
> File "/usr/lib/python2.7/subprocess.py", line 710, in _init_
> errread, errwrite)
> File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
> raise child_exception
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/bigg33k/smoke2graphite/issues/1#issuecomment-207888325

## 

Dave Lemaire
603-325-2257

**Comment by bigg33k** [comment]
I checked in the most recent version so give it a try.   Make sure to
update hostnames, etc.
I saw some things I can do to clean that up as well so I'll try to do so
this week.

On 9 April 2016 at 20:55, Dave lemaire lemairemeister@gmail.com wrote:

> hrm.
> I've made a couple small tweaks since checking that it, but the Popen
> hasn't changed. do you have rrdtool installed?
> I'll update the code when I get a few minutes.
> 
> On 9 April 2016 at 19:59, ragesaq notifications@github.com wrote:
> 
> > Tried that, I get this and I figured I was missing something.
> > 
> > Traceback (most recent call last):
> > File "./s2g.py", line 86, in
> > response=subprocess.Popen(['rrdtool', 'lastupdate',f],
> > stdout=subprocess.PIPE).communicate()[0]
> > File "/usr/lib/python2.7/subprocess.py", line 710, in _init_
> > errread, errwrite)
> > File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
> > raise child_exception
> > 
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > https://github.com/bigg33k/smoke2graphite/issues/1#issuecomment-207888325
> 
> ## 
> 
> Dave Lemaire
> 603-325-2257

## 

Dave Lemaire
603-325-2257
